version: "3"
services:
  db:
    image: postgres:11
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  go_script:
    build: .
    ports: 
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:

