version: '3'
services:
  db:
    build: ./docker/postgres/
    container_name: 'my_psql'
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=simple_todo_db
  app:
    build: .
    container_name: 'my_app'
    ports:
      - 8000:8000
    env_file:
      - .env.db
  proxy:
    build: ./docker/nginx/
    container_name: 'my_nginx'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - 'app'
