version: '3'
services:
  db:
    build: ./postgres/
    container_name: 'my_psql'
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=simple_todo_db
